const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../ficha-editor.js'),'utf8');
const node=(text='')=>({textContent:text,setAttribute(k,v){this[k]=v;}});
const value=node(),change=node(),base=node('80');
const row={querySelector:s=>({'.attr-final-value':value,'.attr-change':change,'.attr-base':base})[s]};
const fields={'score-main':node('99,66'),'improve-main':node('+14%'),'budget-summary':node('66/66'),'attribute-columns':node()};
const save=node(),copy=node(),label=node();
const session={result:{},serial:0,attributeRows:{speed:row}};
const context={session,field:s=>fields[s],id:s=>s==='editor-save'?save:copy,dialog:{querySelector:()=>label},content:{querySelectorAll(){throw Error('Os valores visíveis foram apagados');}}};
vm.createContext(context);
vm.runInContext(source.slice(source.indexOf('  function invalidate(){'),source.indexOf('  function schedule(){'))+source.slice(source.indexOf('  function updateAttribute('),source.indexOf('  function renderAttributes(')),context);
const update=n=>context.updateAttribute(row,{base:80,referencia:85,sistema:n});
update(90);assert.equal(change.textContent,'');
context.invalidate();context.invalidate();
assert.equal(value.textContent,90);assert.equal(fields['score-main'].textContent,'99,66');
assert.equal(session.result,null);assert.equal(save.disabled,true);assert.equal(copy.disabled,true);assert.equal(fields['attribute-columns']['aria-busy'],'true');
update(93);assert.equal(value.textContent,93);assert.equal(change.textContent,'↑');assert.match(change.className,/is-up/);
update(91);assert.equal(change.textContent,'↓');assert.match(change.className,/is-down/);
update(91);assert.equal(change.textContent,'');
update(null);assert.equal(value.textContent,'—');assert.equal(change.textContent,'');
update(92);assert.equal(change.textContent,'');assert.equal(base.textContent,'80');
console.log('OK: números preservados durante alterações rápidas; alta, queda, igualdade e ausência; salvamento bloqueado enquanto pendente.');
