'use strict';
const $=s=>document.querySelector(s);
const texto=v=>Array.isArray(v)?(v.length?v.join(', '):'Nenhum'):(v===null||v===undefined||v===''?'Não informado':String(v));
const seguro=v=>texto(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(c){const r=await fetch(c,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Consulta local indisponível');return d;}
function preencher(id,pares){const alvo=$(id);alvo.innerHTML='';for(const [n,v] of pares){const t=document.importNode($('#linha').content,true);t.querySelector('dt').textContent=n;t.querySelector('dd').innerHTML=seguro(v);alvo.append(t);}}
function parametros(){return {card:$('#card-id').value.trim(),funcao:$('#funcao').value,tecnico:$('#tecnico').value};}
function caminho(rota){const p=parametros();return rota+'?card_id='+encodeURIComponent(p.card)+'&funcao_id='+encodeURIComponent(p.funcao)+'&tecnico_id='+encodeURIComponent(p.tecnico);}
function apresentar(r,paridade){const c=r.carta,out=r.resultado||{};$('#resumo').innerHTML=r.ok?'<h2>Resultado — '+seguro(c.nome||c.card_id)+'</h2><p class="nota">Nota: '+seguro(out.nota)+'</p><p>Função '+seguro(r.funcao.nome)+' · Técnico '+seguro(r.tecnico.nome)+' · multiplicador '+seguro(r.tecnico.multiplicador)+'</p>':'<h2>Simulação bloqueada</h2><p class="aviso">'+seguro(texto(r.falhas||['gate recusou a avaliação']))+'</p>';preencher('#carta',[['Carta',(c.nome||'Sem nome')+' (#'+(c.card_id||'—')+')'],['Posição',c.posicao],['Overall',c.overall],['Orçamento',c.orcamento],['Dimensões por ID',JSON.stringify(c.dimensoes)],['Atributos',(c.atributos||[]).map(x=>(x.codigo||x.indice_otimizador)+': '+x.valor).join(' · ')],['Habilidades por ID',(c.habilidades||[]).map(h=>'#'+h.skill_id).join(', ')||'Nenhuma'],['Cardinalidades',JSON.stringify(c.cardinalidades)]]);preencher('#resultado',r.ok?[['Barras',JSON.stringify(out.barras)],['Gasto',out.gasto],['Sobra',out.sobra],['Boosts (índices)',texto(out.boost_indices)],['Habilidades escolhidas (IDs)',texto(out.habilidades)],['Ímpetos fabricados',texto(out.impetos_fabricados)],['Atributos em campo',texto(out.atributos_em_campo)]]:[['Contrato',r.regua.contrato],['Motivos',texto(r.falhas)]]);$('#gates').innerHTML=(r.gates||[]).map(g=>'<li class="'+(g.ok?'ok':'falha')+'">'+(g.ok?'✓':'×')+' <strong>'+seguro(g.nome)+'</strong> — '+seguro(JSON.stringify(g.detalhe))+'</li>').join('');preencher('#validacao',paridade?[['Paridade',paridade.ok?'Aprovada':'Reprovada'],['Tipo',paridade.tipo],['Vetor esperado',paridade.vetor_esperado_sha256],['Vetor calculado',paridade.vetor_calculado_sha256],['Rótulos',paridade.renomear_texto_nao_muda_calculo?'Não influenciam o cálculo':'Falha']]:[['Modo','Clique em Validar paridade para comparar a equação aprovada com o cálculo inline.'],['Contrato',r.regua.contrato],['Proveniência',r.proveniencia]]);$('#detalhes').hidden=false;}
async function executar(validar){const p=parametros();if(!p.card||!p.funcao||!p.tecnico)return;const b=validar?$('#validar'):$('#simular');b.disabled=true;b.textContent='Consultando…';try{const d=await api(caminho(validar?'/api/validar':'/api/simular'));apresentar(validar?d.simulacao:d,validar?d.paridade:null);}catch(e){$('#resumo').innerHTML='<h2>Resultado</h2><p class="falha">'+seguro(e.message)+'</p>';$('#detalhes').hidden=true;}finally{b.disabled=false;b.textContent=validar?'Validar paridade':'Simular';}}
async function carregar(){try{const x=await Promise.all([api('/api/saude'),api('/api/catalogos')]),s=x[0],c=x[1];$('#estado').textContent=s.contrato+' · '+(s.pode_rodar?'apto':'bloqueado');$('#estado').className='selo '+(s.pode_rodar?'ok':'erro');$('#funcao').innerHTML=c.funcoes.map(x=>'<option value="'+x.funcao_id+'">'+seguro(x.nome)+' (#'+x.funcao_id+')</option>').join('');$('#tecnico').innerHTML=c.tecnicos.map(x=>'<option value="'+x.tecnico_id+'">'+seguro(x.nome)+' (#'+x.tecnico_id+' · '+seguro(x.proficiencia)+')</option>').join('');}catch(e){$('#estado').textContent='Contrato indisponível';$('#estado').className='selo erro';$('#resumo').innerHTML='<h2>Resultado</h2><p class="falha">'+seguro(e.message)+'</p>';}}
$('#simular').addEventListener('click',()=>executar(false));$('#validar').addEventListener('click',()=>executar(true));$('#card-id').addEventListener('keydown',e=>{if(e.key==='Enter')executar(false)});carregar();
