begin;
alter table clube_novo.build
  add column b1 numeric,
  add column b_corpo numeric,
  add column b_pe_ruim numeric,
  add column b_estilo numeric,
  add column b_ia numeric,
  add column b_total numeric,
  add column nota_final numeric,
  add column barras jsonb,
  add column impeto jsonb,
  add column tecnico_id bigint references clube_novo.tecnico_jogo(id),
  add column tecnico_nome text,
  add column habilidades jsonb,
  add column vals jsonb,
  add column vals_tela jsonb,
  add column origem text,
  add column estilo text,
  add column sobra numeric,
  add column receita_versao integer,
  add column motor_versao text,
  add column rodado_em timestamptz,
  add column bonus_rodado_em timestamptz,
  add column recalcular boolean not null default false,
  add column motivo_recalculo text,
  add column extras jsonb,
  add column linha jsonb,
  add column linha_gerada_em timestamptz,
  add column arows jsonb,
  add column linha_enxuta jsonb,
  add column falta_pool jsonb;
commit;
