begin;
alter table clube_novo.build
  drop column if exists falta_pool,
  drop column if exists linha_enxuta,
  drop column if exists arows,
  drop column if exists linha_gerada_em,
  drop column if exists linha,
  drop column if exists extras,
  drop column if exists motivo_recalculo,
  drop column if exists recalcular,
  drop column if exists bonus_rodado_em,
  drop column if exists rodado_em,
  drop column if exists motor_versao,
  drop column if exists receita_versao,
  drop column if exists sobra,
  drop column if exists estilo,
  drop column if exists origem,
  drop column if exists vals_tela,
  drop column if exists vals,
  drop column if exists habilidades,
  drop column if exists tecnico_nome,
  drop column if exists tecnico_id,
  drop column if exists impeto,
  drop column if exists barras,
  drop column if exists nota_final,
  drop column if exists b_total,
  drop column if exists b_ia,
  drop column if exists b_estilo,
  drop column if exists b_pe_ruim,
  drop column if exists b_corpo,
  drop column if exists b1;
commit;
