'use strict';
const $=s=>document.querySelector(s);
const texto=v=>Array.isArray(v)?(v.length?v.join(', '):'Nenhum'):(v===null||v===undefined||v===''?'Não informado':String(v));
const seguro=v=>texto(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(c){const r=await fetch(c,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Consulta local indisponível');return d;}
function preencher(id,pares){const alvo=$(id);alvo.innerHTML='';for(const [n,v] of pares){const t=document.importNode($('#linha').content,true);t.querySelector('dt').textContent=n;t.querySelector('dd').innerHTML=seguro(v);alvo.append(t);}}
function trocarAba(nome){document.querySelectorAll('.aba').forEach(x=>x.hidden=x.id!=='aba-'+nome);document.querySelectorAll('[data-aba]').forEach(x=>x.classList.toggle('aba-ativa',x.dataset.aba===nome));}
function parametros(){return {card:$('#card-id').value.trim(),funcao:$('#funcao').value,tecnico:$('#tecnico').value};}
function caminho(rota){const p=parametros();return rota+'?card_id='+encodeURIComponent(p.card)+'&funcao_id='+encodeURIComponent(p.funcao)+'&tecnico_id='+encodeURIComponent(p.tecnico);}
function linhaVazia(id,msg,colunas){$(id).innerHTML='<tr><td colspan="'+(colunas||5)+'">'+seguro(msg)+'</td></tr>';}
const ESTADOS_FILA={parado:'Parado',rodando:'Rodando',pausando:'Pausando',pausado:'Pausado',encerrando:'Encerrando',encerrado:'Encerrado',interrompido:'Interrompido','concluído':'Concluído',concluido:'Concluído',falhou:'Falhou',aguardando_contrato_de_integracao:'Aguardando contrato da Integração'};
function rotuloEstado(estado){return ESTADOS_FILA[estado]||texto(estado);}
let temporizadorLinhaAtual=null;
let temporizadorFila=null;
let atualizandoFila=false;
const buildsCampeasPorLinha=new Map();
function timestampInicio(x){return x&&((x.iniciada_em)||(x.otimizador_iniciado_em));}
function timestampFim(x){return x&&((x.finalizada_em)||(x.otimizador_finalizado_em));}
function duracaoLegivel(ms){const total=Math.max(0,Math.floor(ms/1000)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;if(total<60)return s+' s';return (h?h+' h ':'')+(m?m+' min ':'')+s+' s';}
function duracaoFinal(x){const segundos=x.duracao_segundos??x.segundos;if(segundos!==null&&segundos!==undefined&&segundos!==''&&Number.isFinite(Number(segundos)))return duracaoLegivel(Number(segundos)*1000);const inicio=timestampInicio(x),fim=timestampFim(x);if(!inicio&&!fim&&x.estado==='pendente')return 'Aguardando processamento';const a=Date.parse(inicio),b=Date.parse(fim);return Number.isFinite(a)&&Number.isFinite(b)&&b>=a?duracaoLegivel(b-a):'Duração não disponível';}
function duracaoCompacta(ms){const total=Math.max(0,Math.round(Number(ms)/10)/100),h=Math.floor(total/3600),resto=total-(h*3600),m=Math.floor(resto/60),s=resto-(m*60),segundos=(valor,doisDigitos)=>{const inteiro=Math.floor(valor),cent=Math.round((valor-inteiro)*100),base=(doisDigitos?String(inteiro).padStart(2,'0'):String(inteiro));return cent?base+'.'+String(cent).padStart(2,'0').replace(/0+$/,''):base;};if(total<60)return segundos(total,false)+'s';return (h?h+'h':'')+m+'m'+segundos(s,true)+'s';}
function duracaoFinalCompacta(x){const segundos=x.duracao_segundos??x.segundos;if(segundos!==null&&segundos!==undefined&&segundos!==''&&Number.isFinite(Number(segundos)))return duracaoCompacta(Number(segundos)*1000);const inicio=timestampInicio(x),fim=timestampFim(x);if(!inicio&&!fim&&x.estado==='pendente')return 'Aguardando processamento';const a=Date.parse(inicio),b=Date.parse(fim);return Number.isFinite(a)&&Number.isFinite(b)&&b>=a?duracaoCompacta(b-a):'Duração não disponível';}
function atualizarTemposEmProcessamento(){document.querySelectorAll('[data-inicio-processamento]').forEach(alvo=>{const inicio=Date.parse(alvo.dataset.inicioProcessamento);if(Number.isFinite(inicio))alvo.textContent='Em processamento há '+duracaoLegivel(Date.now()-inicio);});}
function limparContadorLinhaAtual(){if(temporizadorLinhaAtual!==null){window.clearInterval(temporizadorLinhaAtual);temporizadorLinhaAtual=null;}const destaque=$('#progresso-ao-vivo');destaque.hidden=true;destaque.textContent='';}
function pintarContadorLinhaAtual(linha){limparContadorLinhaAtual();const inicio=Date.parse(timestampInicio(linha));if(!linha||linha.estado!=='processando'||!Number.isFinite(inicio))return;const campo=document.createElement('div');campo.id='tempo-linha-atual';campo.innerHTML='<dt>Em processamento há</dt><dd id="contador-linha-atual"></dd>';$('#linha-atual').append(campo);const atualizar=()=>{const tempo=duracaoLegivel(Date.now()-inicio),alvo=$('#contador-linha-atual'),destaque=$('#progresso-ao-vivo');if(alvo)alvo.textContent=tempo;destaque.hidden=false;destaque.textContent='Processando agora: linha '+linha.linha_id+' · '+(linha.carta_rotulo||linha.card_id)+' · há '+tempo;atualizarTemposEmProcessamento();};atualizar();temporizadorLinhaAtual=window.setInterval(atualizar,1000);}
function aplicarAcoes(acoes,confirmacao){const a=acoes||{},c=confirmacao||{};$('#preparar-fila').disabled=true;$('#iniciar-fila').disabled=!(a.iniciar===true||a.retomar===true);$('#iniciar-fila').textContent=a.iniciar===true?'Iniciar':a.retomar===true?'Retomar':'Iniciar';$('#pausar-fila').disabled=a.pausar!==true;$('#parar-fila').disabled=!(a.parar===true&&c.parar_exige_confirmacao===true);$('#abrir-console').disabled=a.console!==true;}
function agendarAtualizacaoFila(estado){if(temporizadorFila!==null){window.clearTimeout(temporizadorFila);temporizadorFila=null;}if(['rodando','pausando','encerrando'].includes(estado))temporizadorFila=window.setTimeout(atualizarFila,3000);}
function classeLinhaFila(estado){return 'linha-'+String(estado||'desconhecido').replace(/[^a-z0-9_-]/gi,'-');}
function tempoNaFila(x){const inicio=timestampInicio(x);if(x.estado==='processando'&&inicio&&Number.isFinite(Date.parse(inicio)))return '<span class="tempo-em-processamento" data-inicio-processamento="'+seguro(inicio)+'"></span>';return seguro(duracaoFinal(x));}
function buildsComparadas(x){const n=x.builds_comparadas;if(n!==null&&n!==undefined&&n!==''&&Number.isInteger(Number(n))&&Number(n)>=0)return String(n);if(x.estado==='pendente')return 'Aguardando processamento';if(x.estado==='processando')return 'Calculando…';return 'Não registrada';}
function pintarFila(d){const t=d.totais||{};const execucao=d.execucao||{};const estado=execucao.estado||d.estado;const itens=[['Cartas selecionadas',t.cartas_selecionadas],['Linhas geradas',t.linhas_geradas],['Pendentes',t.pendentes],['Em processamento',t.em_processamento],['Concluídas',t.concluidas],['Bloqueadas',t.bloqueadas],['Interrompidas',t.interrompidas],['Falhas',t.falhas]];$('#totais-fila').innerHTML=itens.map(x=>'<div class="total"><span>'+seguro(x[0])+'</span><strong>'+seguro(x[1]||0)+'</strong></div>').join('');$('#estado-execucao').textContent=rotuloEstado(estado);$('#fila-aviso').textContent=d.mensagem||('Lote de teste selado: '+texto(d.lote_id));aplicarAcoes(d.acoes,d.confirmacao);preencher('#linha-atual',d.linha_atual?[['Linha',d.linha_atual.linha_id],['Carta',d.linha_atual.carta_rotulo||d.linha_atual.card_id],['Função',d.linha_atual.funcao_rotulo||d.linha_atual.funcao_id],['Posição',d.linha_atual.posicao_rotulo||d.linha_atual.posicao_id],['Estado',rotuloEstado(d.linha_atual.estado)],['Motivo',texto(d.linha_atual.motivo)]]:[['Estado','Nenhuma linha em processamento.']]);pintarContadorLinhaAtual(d.linha_atual);agendarAtualizacaoFila(estado);if(!d.disponivel){linhaVazia('#linhas-fila',d.mensagem,8);$('#eventos-fila').textContent='Sem eventos reais: '+d.origem;return;}const linhas=d.itens||[];$('#linhas-fila').innerHTML=linhas.map((x,indice)=>'<tr class="'+classeLinhaFila(x.estado)+'"><td class="indice-fila" title="Linha técnica '+seguro(x.linha_id)+'">'+(indice+1)+'</td><td>'+seguro(x.carta_rotulo||x.card_id)+'</td><td>'+seguro(x.funcao_rotulo||'ID '+x.funcao_id+' · catálogo ausente')+'</td><td>'+seguro(x.posicao_rotulo||'ID '+x.posicao_id+' · catálogo ausente')+'</td><td>'+seguro(rotuloEstado(x.estado))+'</td><td>'+tempoNaFila(x)+'</td><td>'+seguro(buildsComparadas(x))+'</td><td>'+seguro(texto(x.motivo||x.erro))+'</td></tr>').join('')||'<tr><td colspan="8">Nenhuma linha pendente.</td></tr>';atualizarTemposEmProcessamento();}
function pontuacaoFinal(x){const nota=x.pontuacao_final??x.b1;if(nota!==null&&nota!==undefined&&nota!=='')return nota;return x.estado==='pendente'?'Aguardando processamento':'Pontuação não informada';}
function barrasCompactas(x){const barras=x.barras;if(!barras||typeof barras!=='object'||Array.isArray(barras))return {texto:'Barras não informadas',detalhe:''};const pares=Object.entries(barras);return {texto:pares.map(([,v])=>v).join(' · '),detalhe:pares.map(([k,v])=>k+': '+v).join(' · ')};}
function resultadoOuMotivo(x){if(x.estado!=='concluido')return {texto:x.motivo||x.erro||'Motivo não informado',detalhe:''};const partes=['Build calculada'];const detalhes=[];if(x.tecnico_rotulo)partes.push('técnico '+x.tecnico_rotulo);const barras=barrasCompactas(x);if(barras.texto!=='Barras não informadas'){partes.push(barras.texto);if(barras.detalhe)detalhes.push('Barras: '+barras.detalhe);}const habilidades=x.habilidades_adicionais_rotulo||[];if(habilidades.length){partes.push('habilidades: '+habilidades.join(', '));detalhes.push('Habilidades adicionadas: '+habilidades.join(', '));}return {texto:partes.join(' · '),detalhe:detalhes.join(' | ')};}
function botaoBuildCampea(x){if(x.estado!=='concluido')return '—';const chave=String(x.linha_id);buildsCampeasPorLinha.set(chave,x);return '<button type="button" class="ver-build-campea" data-linha-id="'+seguro(chave)+'">Ver build campeã</button>';}
function abrirBuildCampea(linhaId){const x=buildsCampeasPorLinha.get(String(linhaId));if(!x)return;const barras=barrasCompactas(x),habilidades=(x.habilidades_adicionais_rotulo||[]);$('#build-campea-aviso').textContent=(x.carta_rotulo||x.card_id)+' · '+(x.funcao_rotulo||('ID '+x.funcao_id))+' · '+(x.posicao_rotulo||('ID '+x.posicao_id));preencher('#build-campea-detalhe',[['Barras vencedoras',barras.detalhe||'Não registradas'],['Técnico vencedor',x.tecnico_rotulo||'Não registrado'],['Habilidades adicionais vencedoras',habilidades.length?habilidades.join(' · '):'Nenhuma registrada'],['Ímpeto adicional',x.impeto_adicional_codigo===null||x.impeto_adicional_codigo===undefined?'Não registrado na saída persistida deste lote':x.impeto_adicional_codigo],['Pontuação final',pontuacaoFinal(x)],['Builds comparadas',buildsComparadas(x)]]);const dialog=$('#dialog-build-campea');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');}
function pintarResultados(d){$('#resultados-aviso').textContent=d.mensagem||'Nenhum resultado disponível.';buildsCampeasPorLinha.clear();if(!d.disponivel){linhaVazia('#linhas-resultados',d.mensagem,9);return;}const linhas=d.itens||[];$('#linhas-resultados').innerHTML=linhas.map(x=>{const resumo=resultadoOuMotivo(x);return '<tr><td>'+seguro(x.carta_rotulo||x.card_id)+'</td><td>'+seguro(x.funcao_rotulo||'ID '+x.funcao_id+' · catálogo ausente')+'</td><td>'+seguro(x.posicao_rotulo||'ID '+x.posicao_id+' · catálogo ausente')+'</td><td>'+seguro(rotuloEstado(x.estado))+'</td><td>'+seguro(pontuacaoFinal(x))+'</td><td class="tempo-resultado">'+seguro(duracaoFinalCompacta(x))+'</td><td>'+botaoBuildCampea(x)+'</td><td>'+seguro(buildsComparadas(x))+'</td><td><span class="resultado-resumo" title="'+seguro(resumo.detalhe)+'">'+seguro(resumo.texto)+'</span></td></tr>';}).join('')||'<tr><td colspan="9">Nenhum resultado final.</td></tr>';}
async function atualizarFila(){if(atualizandoFila)return;atualizandoFila=true;const botao=$('#atualizar-fila'),textoOriginal=botao.textContent;botao.disabled=true;botao.textContent='Atualizando…';try{const s=await api('/api/fila/status');pintarFila(s);const [e,r]=await Promise.all([api('/api/fila/eventos'),api('/api/resultados')]);pintarResultados(r);$('#eventos-fila').textContent=JSON.stringify(e.itens||[],null,2);}catch(e){$('#fila-aviso').textContent=e.message;}finally{atualizandoFila=false;botao.disabled=false;botao.textContent=textoOriginal;}}
async function acaoFila(acao,corpo){const botao=acao==='iniciar'?$('#iniciar-fila'):acao==='pausar'?$('#pausar-fila'):acao==='parar'?$('#parar-fila'):null;const original=botao&&botao.textContent;if(botao){botao.disabled=true;botao.textContent=acao==='iniciar'?'Iniciando…':acao==='pausar'?'Pausando…':'Parando…';}$('#fila-aviso').textContent='Enviando comando de '+acao+' ao lote de teste…';try{const r=await fetch('/api/fila/'+acao,{method:'POST',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify(corpo||{})}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Ação de fila indisponível');await atualizarFila();}catch(e){$('#fila-aviso').textContent=e.message;}finally{if(botao){botao.disabled=false;botao.textContent=original;}}}
function confirmarParar(){if(window.confirm('Parar este lote de TESTE? As linhas já concluídas serão preservadas; as pendentes serão marcadas como interrompidas e nada será publicado.'))acaoFila('parar',{confirmado:true});}
function apresentar(r,paridade){const c=r.carta,out=r.resultado||{};$('#resumo').innerHTML=r.ok?'<h3>Resultado — '+seguro(c.nome||c.card_id)+'</h3><p class="nota">Nota: '+seguro(out.nota)+'</p><p>Função '+seguro(r.funcao.nome)+' · Técnico '+seguro(r.tecnico.nome)+' · multiplicador '+seguro(r.tecnico.multiplicador)+'</p>':'<h3>Simulação bloqueada</h3><p class="aviso">'+seguro(texto(r.falhas||['gate recusou a avaliação']))+'</p>';preencher('#carta',[['Carta',(c.nome||'Sem nome')+' (#'+(c.card_id||'—')+')'],['Posição',c.posicao],['Overall',c.overall],['Orçamento',c.orcamento],['Dimensões por ID',JSON.stringify(c.dimensoes)],['Atributos',(c.atributos||[]).map(x=>(x.codigo||x.indice_otimizador)+': '+x.valor).join(' · ')],['Habilidades por ID',(c.habilidades||[]).map(h=>'#'+h.skill_id).join(', ')||'Nenhuma'],['Cardinalidades',JSON.stringify(c.cardinalidades)]]);preencher('#resultado',r.ok?[['Barras',JSON.stringify(out.barras)],['Gasto',out.gasto],['Sobra',out.sobra],['Boosts (índices)',texto(out.boost_indices)],['Habilidades escolhidas (IDs)',texto(out.habilidades)],['Ímpetos fabricados',texto(out.impetos_fabricados)],['Atributos em campo',texto(out.atributos_em_campo)]]:[['Contrato',r.regua.contrato],['Motivos',texto(r.falhas)]]);$('#gates').innerHTML=(r.gates||[]).map(g=>'<li class="'+(g.ok?'ok':'falha')+'">'+(g.ok?'✓':'×')+' <strong>'+seguro(g.nome)+'</strong> — '+seguro(JSON.stringify(g.detalhe))+'</li>').join('');preencher('#validacao',paridade?[['Paridade',paridade.ok?'Aprovada':'Reprovada'],['Tipo',paridade.tipo],['Vetor esperado',paridade.vetor_esperado_sha256],['Vetor calculado',paridade.vetor_calculado_sha256],['Rótulos',paridade.renomear_texto_nao_muda_calculo?'Não influenciam o cálculo':'Falha']]:[['Modo','Clique em Validar paridade para comparar a equação aprovada com o cálculo inline.'],['Contrato',r.regua.contrato],['Proveniência',r.proveniencia]]);$('#detalhes').hidden=false;}
async function executar(validar){const p=parametros();if(!p.card||!p.funcao||!p.tecnico)return;const b=validar?$('#validar'):$('#simular');b.disabled=true;b.textContent='Consultando…';try{const d=await api(caminho(validar?'/api/validar':'/api/simular'));apresentar(validar?d.simulacao:d,validar?d.paridade:null);}catch(e){$('#resumo').innerHTML='<h3>Resultado</h3><p class="falha">'+seguro(e.message)+'</p>';$('#detalhes').hidden=true;}finally{b.disabled=false;b.textContent=validar?'Validar paridade':'Simular';}}
async function carregar(){try{const x=await Promise.all([api('/api/saude'),api('/api/catalogos')]),s=x[0],c=x[1];$('#estado').textContent=s.contrato+' · '+(s.pode_rodar?'apto':'bloqueado');$('#estado').className='selo '+(s.pode_rodar?'ok':'erro');$('#funcao').innerHTML=c.funcoes.map(x=>'<option value="'+x.funcao_id+'">'+seguro(x.nome)+' (#'+x.funcao_id+')</option>').join('');$('#tecnico').innerHTML=c.tecnicos.map(x=>'<option value="'+x.tecnico_id+'">'+seguro(x.nome)+' (#'+x.tecnico_id+' · '+seguro(x.proficiencia)+')</option>').join('');await atualizarFila();}catch(e){$('#estado').textContent='Contrato indisponível';$('#estado').className='selo erro';$('#fila-aviso').textContent=e.message;}}
document.querySelectorAll('[data-aba]').forEach(x=>x.addEventListener('click',()=>trocarAba(x.dataset.aba)));$('#simular').addEventListener('click',()=>executar(false));$('#validar').addEventListener('click',()=>executar(true));$('#preparar-fila').addEventListener('click',()=>acaoFila('criar'));$('#iniciar-fila').addEventListener('click',()=>acaoFila('iniciar'));$('#pausar-fila').addEventListener('click',()=>acaoFila('pausar'));$('#parar-fila').addEventListener('click',confirmarParar);$('#abrir-console').addEventListener('click',()=>acaoFila('console'));$('#atualizar-fila').addEventListener('click',atualizarFila);$('#card-id').addEventListener('keydown',e=>{if(e.key==='Enter')executar(false)});$('#linhas-resultados').addEventListener('click',e=>{const botao=e.target.closest('.ver-build-campea');if(botao)abrirBuildCampea(botao.dataset.linhaId)});$('#fechar-build-campea').addEventListener('click',()=>$('#dialog-build-campea').close());carregar();
