'use strict';
const $=s=>document.querySelector(s);
const texto=v=>Array.isArray(v)?(v.length?v.join(', '):'Nenhum'):(v===null||v===undefined||v===''?'Não informado':String(v));
const seguro=v=>texto(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(c){const r=await fetch(c,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Consulta local indisponível');return d;}
function preencher(id,pares){const alvo=$(id);alvo.innerHTML='';for(const [n,v] of pares){const t=document.importNode($('#linha').content,true);t.querySelector('dt').textContent=n;t.querySelector('dd').innerHTML=seguro(v);alvo.append(t);}}
function trocarAba(nome){document.querySelectorAll('.aba').forEach(x=>x.hidden=x.id!=='aba-'+nome);document.querySelectorAll('[data-aba]').forEach(x=>x.classList.toggle('aba-ativa',x.dataset.aba===nome));}
function parametros(){return {card:$('#card-id').value.trim(),funcao:$('#funcao').value,tecnico:$('#tecnico').value};}
function caminho(rota){const p=parametros();return rota+'?card_id='+encodeURIComponent(p.card)+'&funcao_id='+encodeURIComponent(p.funcao)+'&tecnico_id='+encodeURIComponent(p.tecnico);}
function linhaVazia(id,msg){$(id).innerHTML='<tr><td colspan="5">'+seguro(msg)+'</td></tr>';}
const ESTADOS_FILA={parado:'Parado',rodando:'Rodando',pausando:'Pausando',pausado:'Pausado','concluído':'Concluído',concluido:'Concluído',falhou:'Falhou',aguardando_contrato_de_integracao:'Aguardando contrato da Integração'};
function rotuloEstado(estado){return ESTADOS_FILA[estado]||texto(estado);}
function aplicarAcoes(acoes){const a=acoes||{};$('#preparar-fila').disabled=true;$('#iniciar-fila').disabled=!(a.iniciar===true||a.retomar===true);$('#iniciar-fila').textContent=a.iniciar===true?'Iniciar':a.retomar===true?'Retomar':'Iniciar';$('#pausar-fila').disabled=a.parar!==true;$('#parar-fila').disabled=true;$('#abrir-console').disabled=a.console!==true;}
function pintarFila(d){const t=d.totais||{};const execucao=d.execucao||{};const itens=[['Cartas selecionadas',t.cartas_selecionadas],['Linhas geradas',t.linhas_geradas],['Pendentes',t.pendentes],['Em processamento',t.em_processamento],['Concluídas',t.concluidas],['Bloqueadas',t.bloqueadas],['Falhas',t.falhas]];$('#totais-fila').innerHTML=itens.map(x=>'<div class="total"><span>'+seguro(x[0])+'</span><strong>'+seguro(x[1]||0)+'</strong></div>').join('');$('#estado-execucao').textContent=rotuloEstado(execucao.estado||d.estado);$('#fila-aviso').textContent=d.mensagem||('Lote de teste selado: '+texto(d.lote_id));aplicarAcoes(d.acoes);preencher('#linha-atual',d.linha_atual?[['Linha',d.linha_atual.linha_id],['Carta',d.linha_atual.card_id],['Função',d.linha_atual.funcao_id],['Posição',d.linha_atual.posicao_id],['Estado',rotuloEstado(d.linha_atual.estado)],['Motivo',texto(d.linha_atual.motivo)]]:[['Estado','Nenhuma linha em processamento.']]);if(!d.disponivel){linhaVazia('#linhas-fila',d.mensagem);$('#eventos-fila').textContent='Sem eventos reais: '+d.origem;return;}const linhas=d.itens||[];$('#linhas-fila').innerHTML=linhas.map(x=>'<tr><td>'+seguro(x.card_id)+'</td><td>'+seguro(x.funcao_id)+'</td><td>'+seguro(x.posicao_id)+'</td><td>'+seguro(rotuloEstado(x.estado))+'</td><td>'+seguro(texto(x.motivo||x.erro))+'</td></tr>').join('')||'<tr><td colspan="5">Nenhuma linha pendente.</td></tr>';}
function pintarResultados(d){$('#resultados-aviso').textContent=d.mensagem||'Nenhum resultado disponível.';if(!d.disponivel){linhaVazia('#linhas-resultados',d.mensagem);return;}const linhas=d.itens||[];$('#linhas-resultados').innerHTML=linhas.map(x=>'<tr><td>'+seguro(x.card_id)+'</td><td>'+seguro(x.funcao_id)+'</td><td>'+seguro(x.posicao_id)+'</td><td>'+seguro(rotuloEstado(x.estado))+'</td><td>'+seguro(x.resultado||x.motivo||x.erro||'Detalhe não exposto pelo contrato de fila')+'</td></tr>').join('')||'<tr><td colspan="5">Nenhum resultado final.</td></tr>';}
async function atualizarFila(){try{const [s,e,r]=await Promise.all([api('/api/fila/status'),api('/api/fila/eventos'),api('/api/resultados')]);pintarFila(s);pintarResultados(r);$('#eventos-fila').textContent=JSON.stringify(e.itens||[],null,2);}catch(e){$('#fila-aviso').textContent=e.message;}}
async function acaoFila(acao){try{const r=await fetch('/api/fila/'+acao,{method:'POST',cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.erro||'Ação de fila indisponível');await atualizarFila();}catch(e){$('#fila-aviso').textContent=e.message;}}
function apresentar(r,paridade){const c=r.carta,out=r.resultado||{};$('#resumo').innerHTML=r.ok?'<h3>Resultado — '+seguro(c.nome||c.card_id)+'</h3><p class="nota">Nota: '+seguro(out.nota)+'</p><p>Função '+seguro(r.funcao.nome)+' · Técnico '+seguro(r.tecnico.nome)+' · multiplicador '+seguro(r.tecnico.multiplicador)+'</p>':'<h3>Simulação bloqueada</h3><p class="aviso">'+seguro(texto(r.falhas||['gate recusou a avaliação']))+'</p>';preencher('#carta',[['Carta',(c.nome||'Sem nome')+' (#'+(c.card_id||'—')+')'],['Posição',c.posicao],['Overall',c.overall],['Orçamento',c.orcamento],['Dimensões por ID',JSON.stringify(c.dimensoes)],['Atributos',(c.atributos||[]).map(x=>(x.codigo||x.indice_otimizador)+': '+x.valor).join(' · ')],['Habilidades por ID',(c.habilidades||[]).map(h=>'#'+h.skill_id).join(', ')||'Nenhuma'],['Cardinalidades',JSON.stringify(c.cardinalidades)]]);preencher('#resultado',r.ok?[['Barras',JSON.stringify(out.barras)],['Gasto',out.gasto],['Sobra',out.sobra],['Boosts (índices)',texto(out.boost_indices)],['Habilidades escolhidas (IDs)',texto(out.habilidades)],['Ímpetos fabricados',texto(out.impetos_fabricados)],['Atributos em campo',texto(out.atributos_em_campo)]]:[['Contrato',r.regua.contrato],['Motivos',texto(r.falhas)]]);$('#gates').innerHTML=(r.gates||[]).map(g=>'<li class="'+(g.ok?'ok':'falha')+'">'+(g.ok?'✓':'×')+' <strong>'+seguro(g.nome)+'</strong> — '+seguro(JSON.stringify(g.detalhe))+'</li>').join('');preencher('#validacao',paridade?[['Paridade',paridade.ok?'Aprovada':'Reprovada'],['Tipo',paridade.tipo],['Vetor esperado',paridade.vetor_esperado_sha256],['Vetor calculado',paridade.vetor_calculado_sha256],['Rótulos',paridade.renomear_texto_nao_muda_calculo?'Não influenciam o cálculo':'Falha']]:[['Modo','Clique em Validar paridade para comparar a equação aprovada com o cálculo inline.'],['Contrato',r.regua.contrato],['Proveniência',r.proveniencia]]);$('#detalhes').hidden=false;}
async function executar(validar){const p=parametros();if(!p.card||!p.funcao||!p.tecnico)return;const b=validar?$('#validar'):$('#simular');b.disabled=true;b.textContent='Consultando…';try{const d=await api(caminho(validar?'/api/validar':'/api/simular'));apresentar(validar?d.simulacao:d,validar?d.paridade:null);}catch(e){$('#resumo').innerHTML='<h3>Resultado</h3><p class="falha">'+seguro(e.message)+'</p>';$('#detalhes').hidden=true;}finally{b.disabled=false;b.textContent=validar?'Validar paridade':'Simular';}}
async function carregar(){try{const x=await Promise.all([api('/api/saude'),api('/api/catalogos')]),s=x[0],c=x[1];$('#estado').textContent=s.contrato+' · '+(s.pode_rodar?'apto':'bloqueado');$('#estado').className='selo '+(s.pode_rodar?'ok':'erro');$('#funcao').innerHTML=c.funcoes.map(x=>'<option value="'+x.funcao_id+'">'+seguro(x.nome)+' (#'+x.funcao_id+')</option>').join('');$('#tecnico').innerHTML=c.tecnicos.map(x=>'<option value="'+x.tecnico_id+'">'+seguro(x.nome)+' (#'+x.tecnico_id+' · '+seguro(x.proficiencia)+')</option>').join('');await atualizarFila();}catch(e){$('#estado').textContent='Contrato indisponível';$('#estado').className='selo erro';$('#fila-aviso').textContent=e.message;}}
document.querySelectorAll('[data-aba]').forEach(x=>x.addEventListener('click',()=>trocarAba(x.dataset.aba)));$('#simular').addEventListener('click',()=>executar(false));$('#validar').addEventListener('click',()=>executar(true));$('#preparar-fila').addEventListener('click',()=>acaoFila('criar'));$('#iniciar-fila').addEventListener('click',()=>acaoFila('iniciar'));$('#pausar-fila').addEventListener('click',()=>acaoFila('pausar'));$('#abrir-console').addEventListener('click',()=>acaoFila('console'));$('#atualizar-fila').addEventListener('click',atualizarFila);$('#card-id').addEventListener('keydown',e=>{if(e.key==='Enter')executar(false)});carregar();
